// Miglore OS — 首页静态演示数据（V1 阶段未连库，后续由 /api/dashboard 替换）
import type { DashboardData } from './types';

export const mockDashboard: DashboardData = {
  hero: {
    date: '8月15日',
    weekday: '周六',
    streak_days: 12,
    career_goal: 'DevOps 工程师',
    active_track: {
      id: 1,
      title: 'DevOps 学习计划',
      stage: '阶段二 · Docker 容器化',
      progress: 68,
    },
  },
  continue_learning: [
    {
      id: 10,
      type: 'learning',
      title: 'Docker Compose 编排实战',
      status: 'in_progress',
      priority: 3,
      due_date: '2026-08-16',
      track: 'DevOps 学习计划',
    },
    {
      id: 11,
      type: 'learning',
      title: 'systemd 服务单元深入',
      status: 'in_progress',
      priority: 2,
      due_date: '2026-08-17',
      track: 'DevOps 学习计划',
    },
    {
      id: 12,
      type: 'learning',
      title: 'Nginx 反向代理进阶',
      status: 'todo',
      priority: 2,
      due_date: '2026-08-18',
      track: 'DevOps 学习计划',
    },
    {
      id: 13,
      type: 'learning',
      title: 'MySQL 主从复制实践',
      status: 'todo',
      priority: 1,
      due_date: '2026-08-19',
      track: 'DevOps 学习计划',
    },
  ],
  learning_progress: [
    { id: 1, name: 'Nginx', level: 4, target_level: 5, status: 'learning' },
    { id: 2, name: 'Docker', level: 4, target_level: 5, status: 'learning' },
    { id: 3, name: 'MySQL', level: 3, target_level: 5, status: 'learning' },
    { id: 4, name: 'Linux', level: 4, target_level: 5, status: 'learning' },
    { id: 5, name: 'Python', level: 3, target_level: 5, status: 'learning' },
    { id: 6, name: 'Svelte', level: 2, target_level: 4, status: 'learning' },
  ],
  featured_projects: [
    {
      id: 1,
      name: 'Miglore OS',
      description: '个人成长操作系统 — 学习、求职、项目、任务一体化',
      tech_stack: 'Svelte · Flask · MySQL',
      status: 'active',
      progress: 12,
      featured: true,
    },
    {
      id: 2,
      name: 'DevOps Lab',
      description: 'Nginx / systemd / Docker Compose 实操实验室',
      tech_stack: 'Nginx · Docker · MySQL',
      status: 'active',
      progress: 80,
      featured: true,
    },
    {
      id: 3,
      name: '高济帮助台自动接单',
      description: 'KF5 工单系统纯 API 常驻接单机器人',
      tech_stack: 'Python · KF5 API',
      status: 'done',
      progress: 100,
      featured: true,
    },
  ],
  today_tasks: [
    { id: 21, type: 'project', title: '完成 API 设计文档评审', status: 'todo', priority: 3, due_date: '2026-08-15', project: 'Miglore OS' },
    { id: 22, type: 'daily', title: '面试复盘：XX 公司一面', status: 'todo', priority: 2, due_date: '2026-08-15' },
    { id: 23, type: 'daily', title: '更新投递记录表', status: 'todo', priority: 2, due_date: '2026-08-15' },
    { id: 24, type: 'learning', title: 'Docker Compose 实战练习', status: 'todo', priority: 1, due_date: '2026-08-15', track: 'DevOps 学习计划' },
  ],
  recent_activity: [
    { id: 101, log_date: '2026-08-14', content: '完成 MySQL 主从原理学习 + Compose 编排练习，跑通 backend+mysql+nginx 三容器', duration_min: 90, mood: 4 },
    { id: 102, log_date: '2026-08-13', content: '复习 systemd 服务单元：Restart 策略与 Docker 对比实验', duration_min: 45, mood: 4 },
    { id: 103, log_date: '2026-08-12', content: '投递 2 家公司的 DevOps 岗位，更新求职状态', duration_min: 30, mood: 3 },
    { id: 104, log_date: '2026-08-11', content: 'Nginx 反向代理 + 静态缓存配置实战', duration_min: 60, mood: 5 },
    { id: 105, log_date: '2026-08-10', content: '高济帮助台自动接单服务优化，工单响应提速到 2s', duration_min: 120, mood: 4 },
  ],
  career_status: [
    { label: '投递总数', value: 8 },
    { label: '面试中', value: 2 },
    { label: '待面试', value: 1 },
    { label: '已拿 Offer', value: 0 },
  ],
};
